### ISSUE TITLE
feature request: only use first digit of back-reference if not enough exists

### ISSUE THREAD

**Issue by benibela** [BeRo1985/flre#11]
It would be better if e.g.  `\10` would be interpreted as `(?:\1)0`, if there are only 9 groups, instead giving an error. Or `\100` as `(?:\10)0` if there are less than 100.

**Comment by BeRo1985** [comment]
That would introduce only inconsistency and add a bit more complexity to the parser in the regex compiler. Just use simply empty non-capturing-groups to break it, for example `\10(?:)0` or better `\g{10}0` or `\k<10>0` (see http://www.regular-expressions.info/refcapture.html )
