### ISSUE TITLE
feature request: customizable syntax

### ISSUE THREAD

**Issue by benibela** [BeRo1985/flre#12]
It would be nice, if there were flags to enable/disable most  advanced regex escape characters separately. E.g. with a lookup table char -> state flags, instead all the case expressions

For example for XML schema regex, only the following multi-character classes are allowed:  sSiIcCdDwWpP, and neither (?= nor (?- nor (?+ is allowed.

**Comment by BeRo1985** [comment]
I want to keep FLRE simple as possible, so that it does not degenerate as in BRRE, and at the end you only have a lot of bugs like in BRRE. 

Anyway, what's stopping you to write your own regular expression preprocessor?

**Comment by benibela** [comment]
>I want to keep FLRE simple as possible

A lookup table could make it even simpler.

E.g. the entire block of 

         'b','y':begin
          result:=NewNode(ntZEROWIDTH,nil,nil,sfEmptyWordBoundary);
          inc(SourcePosition);
         end;
         'B','Y':begin
          result:=NewNode(ntZEROWIDTH,nil,nil,sfEmptyNonWordBoundary);
          inc(SourcePosition);
         end;
         'A':begin
          result:=NewNode(ntZEROWIDTH,nil,nil,sfEmptyBeginText);
          inc(SourcePosition);
         end;
         'Z':begin
          result:=NewNode(ntZEROWIDTH,nil,nil,sfEmptyEndText);
          inc(SourcePosition);
         end;

could become

    if table[Source[SourcePosition]] <> sfUndefined then begin
             result:=NewNode(ntZEROWIDTH,nil,nil,table[Source[SourcePosition]]);
             inc(SourcePosition);
    end;

>Anyway, what's stopping you to write your own regular expression preprocessor?

Then everrything has to be parsed twice. I thought that would be inefficient

**Comment by BeRo1985** [comment]
With caching it wouldn't be inefficient. And recompiling a regexp every time before the usage without caching is really actually a very bad idea (performance-wise). ;-)
