### ISSUE TITLE
var vs. out

### ISSUE THREAD

**Issue by benibela** [BeRo1985/flre#16]
FPC always complains "Hint: Local variable "captures" does not seem to be initialized", can you use `out` parameters instead `var` for the matchings?

**Comment by BeRo1985** [comment]
FLRE tries to reuse the last captures array of the previous call for as memory manager speed optimization, so you do should use `Captures := nil;` before the first MatchAll call.

**Comment by benibela** [comment]
That seems like a good idea, but PtrMatchAll starts with `SetLength(MultiCaptures,0);`...

**Comment by BeRo1985** [comment]
I've fixed that some minutes ago :)
