### ISSUE TITLE
InitializeFLRE speed

### ISSUE THREAD

**Issue by benibela** [BeRo1985/flre#17]
I was looking at the wrong function in #15  Sry.

Now I have ran my real grep-like program with the real (test) data through the profiler.

FLRE actually spends three times as many instruction cycles in InitializeFLRE/Unicode (179M), than the entire program needs with Sorokin's lib to read its input, generate its output and exit (62M).

**Comment by BeRo1985** [comment]
Fixed by replacing(&removing) InitializeUnicode in InitializeFLRE by external FLREBuildUnicode helper tool, which create constant arrays of these data. :)
