### ISSUE TITLE
French presentation

### ISSUE THREAD

**Issue by RolandChastain** [BeRo1985/flre#2]
Hello!

Why not a presentation in french language there ?

http://www.developpez.net/forums/f21/autres-langages/pascal/

Have you an account? If you don't or if you don't want to make the presentation yourself, I could do it.

Best regards and congratulations for FLRE.

**Comment by BeRo1985** [comment]
I'm a german guy, not french :-) So I can read&write only german&english but not french. My family tree is more than dozens of several generations already in Germany, despite the surname Rosseaux.  My surname is often confused in this context.

**Comment by RolandChastain** [comment]
OK, I understand. So I will present your project myself on the french-speaking forum. Your project looks awesome. I was surprised to compile it without modifications nor warnings with FPC 2.6, Delphi 7 and Delphi XE2.

**Comment by RolandChastain** [comment]
Short french presentation of FLRE.

http://www.developpez.net/forums/blogs/471763-roland-chastain/b777/nouvelle-bibliotheque-pascal-lutilisation-expressions-regulieres/

**Comment by RolandChastain** [comment]
And a download page (pointing to this site).

http://pascal.developpez.com/telecharger/detail/id/4564/FLRE-moins-Fast-Light-Regular-Expressions
