### ISSUE TITLE
negative look ahead

### ISSUE THREAD

**Issue by benibela** [BeRo1985/flre#27]
Does it support negative look aheads? Would be nice, if it did.

The current behaviour is just weird:

```
 f := TFLRE.Create('a(?!b)', []); 
 writeln(f.Find('ab'));  //=> 1

 f := TFLRE.Create('a(?!b)', []);
 writeln(f.Test('ab')); //=> EAccessViolation, State = nil in FLRE:7218 NextMatchCondition:=State^.MatchCondition;
```

**Comment by pyscripter** [comment]
These is really two separate issues.   The first one is issue #42,  Look it up for the fix.
The second is issue #43.  Again look it up for the fix.

Together the above fixes resolve this issue.
