### ISSUE TITLE
Alternation

### ISSUE THREAD

**Issue by RolandChastain** [BeRo1985/flre#3]
Hello Benjamin !

I wrote a little example using alternative expressions. Here is my code.

program alternative;
{$I directives}

uses
  SysUtils,
  Classes,
  FLRE in '..\src\FLRE.pas',
  FLREUnicode in '..\src\FLREUnicode.pas';

const
  SAMPLE: array[0..2] of string = (
    'jeudi',
    '24/09/2015',
    '13:33'
  );

  DAYOFWEEK_PATTERN = '(\w{5,8})';
  DATE_PATTERN = '(\d{2})/(\d{2})/(\d{4})';
  TIME_PATTERN = '(\d{2}):(\d{2})';
  PATTERN = DAYOFWEEK_PATTERN + '|' + DATE_PATTERN + '|' + TIME_PATTERN;

var
  e: TFLRE;
  c: TFLRECaptures;
  i: integer;
  j: integer;

begin
  e := TFLRE.Create(PATTERN, []);

  for i := Low(SAMPLE) to High(SAMPLE) do
    if e.Match(SAMPLE[i], c) then
      for j := 0 to High(c) do
        WriteLn(Format('%d %d %s', [i, j, Copy(SAMPLE[i], c[j].Start, c[j].Length)]));

  e.Free;

  ReadLn;
end.

And here are the results.

0 0 jeudi
0 1 jeudi
0 2
0 3
0 4
0 5
0 6
1 0 24/09/2015
1 1 24/09
1 2 24
1 3 09
1 4 2015
1 5
1 6
2 0 13:33
2 1 13:33
2 2 13
2 3 33
2 4
2 5 13
2 6 33

Can we consider these results as expected results? How can I know by code which subexpression matched the subject?

Best regards.

Roland

P.-S. I am not very used to Github so if I make something wrong please don't hesitate to say it to me.

**Comment by BeRo1985** [comment]
Yes, the results seems to be right, because \w matches also numbers, since it matches all alphanumeric characters, so when you do want only alphas at (\w{5,8}), then you should use rather [A-Za-z] or the POSIX character class [:alpha:] etc. For more infos regarding this see http://www.regular-expressions.info/posixbrackets.html

**Comment by RolandChastain** [comment]
Thank you for your answer. Yes, [A-Za-z] is better in that case than \w, but it doesn't solve the problem. The result is always the same. See the lines where I put an arrow. Logically, shouldn't these lines be empty?

0 0 jeudi
0 1 jeudi
0 2
0 3
0 4
0 5
0 6
1 0 24/09/2015
1 1 24/09 <----
1 2 24
1 3 09
1 4 2015
1 5
1 6
2 0 13:33
2 1 13:33 <----
2 2 13 <----
2 3 33 <----
2 4
2 5 13
2 6 33

That is what I wanted to say. It isn't very important and I don't want to bother you about that. I just wanted to report something that looked strange to me. ;)

**Comment by BeRo1985** [comment]
Can you try the lastest FLRE version from some minutes ago?

**Comment by RolandChastain** [comment]
OK, it's perfect now. Good job!

**Comment by RolandChastain** [comment]
I imagine that "close the issue" means the same as "problem solved", so I close the issue. :)
