### ISSUE TITLE
PtrPosCharSearch still crashes on empty string

### ISSUE THREAD

**Issue by benibela** [BeRo1985/flre#37]
TFLRE.Create('A+', []).Test('')

gives the same as #36

**Comment by benibela** [comment]
It still happens. on 64 bit linux

**Comment by pyscripter** [comment]
I tested on Delphi + Win64.
By the way could you please rerun the xquery test suit to see what fails.  I may be able to help fix some of those.

**Comment by BeRo1985** [comment]
Please try https://github.com/BeRo1985/flre/commit/5aa8a9e032feff7a5790104f2d53fa74c70bb1d9

**Comment by benibela** [comment]
appears to be ok
