### ISSUE TITLE
Access violation when replacing a pattern by an empty string

### ISSUE THREAD

**Issue by RolandChastain** [BeRo1985/flre#4]
Hello!

When I try to replace a pattern by an empty string, I get an access violation (FPC 2.6.4, Windows).

program testreplace;

uses
  Classes, SysUtils, FLRE, FLREUnicode;
  
begin
  with TFLRE.Create('\d', []) do
  begin
    MaximalDFAStates := 65536;
    WriteLn(Replace('a1b', '-'));
    WriteLn(Replace('a1b', '')); // Access violation
    Free;
  end;
end.

Best regards.

Roland

**Comment by BeRo1985** [comment]
Fixed at https://github.com/BeRo1985/flre/commit/8d3e8bdd8b73bcf7e3a6f1b32469c600a7b8bd86 :-)
