### ISSUE TITLE
Prefix factoring in Optimize node produces wrong results

### ISSUE THREAD

**Issue by pyscripter** [BeRo1985/flre#44]
```
FLREInstance := tflre.Create('37|3|2', []);
Writeln(FLREInstance.DumpRegularExpression);
```
Result: (37|2)

If you comment out Prefix factoring lines 14495-a4586 the 
Result: (37|3|2)

Issue #10 is related to this

**Comment by BeRo1985** [comment]
Please test the new possible fix for it.

**Comment by pyscripter** [comment]
It does work.
37|3|2
is converted to: 
(3(?:7|(?:))|2)
which is correct.  Is the above as efficient as
(37?|2)

**Comment by pyscripter** [comment]
By the way have a look at https://pyscripter.blogspot.gr/2018/04/benchmark-of-regular-expression-engines.html
and
https://plus.google.com/u/0/104825163436199563872/posts/GHcoEQ9M1pD

**Comment by pyscripter** [comment]
Questiion:
In the above benchmark adding the rfONLYFASTOPTIMIZATIONS flag does not result in any degradation of speed.   I guess this is because of the nature of the tested reg expressions.  Is this the case?

**Comment by BeRo1985** [comment]
Yes, right, but it depends also on the each-at-end-used subengines in FLRE, because some subengines don't care about so such optimizations in principle (for example the lazy-DFA-based), and some other subengines do care about it in turn.
