### ISSUE TITLE
OnePassNFA will never be used

### ISSUE THREAD

**Issue by pyscripter** [BeRo1985/flre#45]
After your last commits, and as it stands OnePassNFA will never be used and there is no need to CompileOnePassNFA.   All relevant code could be removed without impact.
Is CompileOnePassNFA used by BitStateNFA?

**Comment by BeRo1985** [comment]
The lazy-DFA stuff is only primarly there to find the approximate beginning (and end) of a match very fast, all following subengines (inclding BitstateNFA and OnePassNFA and so on) are used for to confirm and refine the match (including find the paren captures, do lookaheads&lookbehinds, and so on). And lazy-DFA alone (without following subengines after it) will be only used, even if the regex is really simple, in other words: if no captures, no lookaheads, no lookbehinds, and so on are used in a regex.

**Comment by pyscripter** [comment]
I got it.
