### ISSUE TITLE
Calling TFLRE.Create without the second parameter raises an exception

### ISSUE THREAD

**Issue by rchastain** [BeRo1985/flre#55]
Hello!

Calling TFLRE.Create without the second parameter is possible but raises an unhandled exception:

`EFLRE: Unknown regular expression modifier flag`

Is it the expected behaviour?

Regards.

Roland

**Comment by BeRo1985** [comment]
Yes, it is the expected behaviour, because FLRE expects then a input regex string for example like in the form `/regex/flags` for example `/d+/g'

**Comment by rchastain** [comment]
I see. Thank you for the explanation.
