### ISSUE TITLE
Match method returns inconsistent result

### ISSUE THREAD

**Issue by rchastain** [BeRo1985/flre#56]
Hello!
Here is my code:

```
uses
  SysUtils, FLRE;

procedure MatchTest(const APattern, ASubject: TFLRERawByteString);
var
  e: TFLRE;
  c: TFLRECaptures;
begin
  e := TFLRE.Create(APattern, []);
  try
    WriteLn(APattern:10, ASubject:10, e.Match(ASubject, c):10);
  finally
    e.Free;
  end;
end;

begin
  MatchTest('\d+', '123');
  MatchTest('\d+', '123.');
  MatchTest('\d+', '.123');
end.
```

And the result:
```
       \d+       123      TRUE
       \d+      123.      TRUE
       \d+      .123     FALSE
```

Is it the expected behaviour? I would have expected the same result for line 2 and line 3 (both FALSE, or both TRUE).

By the way, I intend to write a tutorial for regular expressions with FLRE. That's why I come here to bore you. :)

Regards.

Roland

**Comment by BeRo1985** [comment]
Yes, it is the expected behaviour. What do you want, is MatchAll (or Match + multiple MatchNext calls)  but not Match.

**Comment by BeRo1985** [comment]
And when `123.` should be also false, you should use anchors and write `\d+$` :-)   

`^` = Begin anchor
`$` = End anchor

**Comment by rchastain** [comment]
OK, thank you.
