### ISSUE TITLE
Simple detection of a pattern into a string

### ISSUE THREAD

**Issue by RolandChastain** [BeRo1985/flre#6]
Hello!

I try to detect a pattern into a string. Here is my current code:

```
const
  SPACE = '\s+';
  SWITCH = '[/-]';
  TEMPLATE = SPACE + SWITCH + '%s' + SPACE;

var
  pattern: string;
  
  e: TFLRE;
  c: TFLRECaptures;
  s: TFLRERawByteString;

begin
  pattern := Format(TEMPLATE, ['[Aa]']);

  e := TFLRE.Create(pattern, []);
  try
    s := ' /A ';
    WriteLn(e.Match(s, c)); // TRUE
    s := '* /A *';
    WriteLn(e.Match(s, c)); // FALSE
  finally
    e.Free;
  end;
```

The second result is surprising, because with the other regular expressions libraries that I know, the result would be TRUE. It would be FALSE only if "^" and "$" anchors were added to the pattern. Right?

The solution I found is to use the following pattern:

```
  TEMPLATE = '.*' + SPACE + SWITCH + '%s' + SPACE + '.*';
```

Is there a better solution?

**Comment by BeRo1985** [comment]
try use MatchAll :) Match does only a anchored search :)

**Comment by RolandChastain** [comment]
OK, thank you.
