### ISSUE TITLE
Access violation on invalid regex

### ISSUE THREAD

**Issue by benibela** [BeRo1985/flre#8]
f := TFLRE.Create('a[]b', []);

=>

  $000000000058FDD1 line 10925 of ../../../components/pascal/import/flre/src/FLRE.pas
  $000000000058C452 line 12167 of ../../../components/pascal/import/flre/src/FLRE.pas
  $00000000005899B7 line 12264 of ../../../components/pascal/import/flre/src/FLRE.pas
  $0000000000589829 line 12390 of ../../../components/pascal/import/flre/src/FLRE.pas
  $0000000000589699 line 12418 of ../../../components/pascal/import/flre/src/FLRE.pas
  $0000000000588F38 line 12489 of ../../../components/pascal/import/flre/src/FLRE.pas
  $0000000000584DEA line 9438 of ../../../components/pascal/import/flre/src/FLRE.pas

**Comment by BeRo1985** [comment]
Fixed in the lastest commit :)
